/**
 * Smart Collections Service
 * AI-powered auto-grouping of clips
 */

import { query } from '../config/database.js';

/**
 * Generate smart collections for user
 */
export async function generateSmartCollections(userId) {
  try {
    // Get user clips
    const clipsResult = await query(
      `SELECT id, content, type, metadata, tags
       FROM clips
       WHERE user_id = $1 AND deleted_at IS NULL
       ORDER BY created_at DESC
       LIMIT 1000`,
      [userId]
    );

    const clips = clipsResult.rows;

    // Group by similarity (simple approach: by type and content similarity)
    const collections = groupClipsBySimilarity(clips);

    return collections;
  } catch (error) {
    console.error('Generate collections error:', error);
    throw error;
  }
}

/**
 * Group clips by similarity
 */
function groupClipsBySimilarity(clips) {
  const collections = [];

  // Group by type
  const byType = {};
  clips.forEach(clip => {
    const type = clip.type || 'text';
    if (!byType[type]) {
      byType[type] = [];
    }
    byType[type].push(clip);
  });

  // Create collections for types with multiple clips
  Object.entries(byType).forEach(([type, typeClips]) => {
    if (typeClips.length >= 3) {
      collections.push({
        name: `${type.charAt(0).toUpperCase() + type.slice(1)} Collection`,
        description: `${typeClips.length} ${type} clips`,
        clips: typeClips.map(c => c.id),
        autoGenerated: true,
        type,
      });
    }
  });

  // Group by tags
  const byTags = {};
  clips.forEach(clip => {
    const tags = clip.tags || [];
    tags.forEach(tag => {
      if (!byTags[tag]) {
        byTags[tag] = [];
      }
      byTags[tag].push(clip);
    });
  });

  // Create collections for popular tags
  Object.entries(byTags).forEach(([tag, tagClips]) => {
    if (tagClips.length >= 3) {
      collections.push({
        name: `#${tag}`,
        description: `${tagClips.length} clips with tag "${tag}"`,
        clips: tagClips.map(c => c.id),
        autoGenerated: true,
        tag,
      });
    }
  });

  // Group by date (recent, today, this week, this month)
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const thisWeek = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
  const thisMonth = new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000);

  const recent = clips.filter(c => new Date(c.created_at) >= today);
  const weekly = clips.filter(c => {
    const date = new Date(c.created_at);
    return date >= thisWeek && date < today;
  });
  const monthly = clips.filter(c => {
    const date = new Date(c.created_at);
    return date >= thisMonth && date < thisWeek;
  });

  if (recent.length >= 3) {
    collections.push({
      name: 'Recent Clips',
      description: `${recent.length} clips from today`,
      clips: recent.map(c => c.id),
      autoGenerated: true,
      timeRange: 'today',
    });
  }

  if (weekly.length >= 3) {
    collections.push({
      name: 'This Week',
      description: `${weekly.length} clips from this week`,
      clips: weekly.map(c => c.id),
      autoGenerated: true,
      timeRange: 'week',
    });
  }

  return collections;
}

/**
 * Save smart collection
 */
export async function saveSmartCollection(userId, collection) {
  try {
    const result = await query(
      `INSERT INTO collections (user_id, name, description, clip_ids, auto_generated)
       VALUES ($1, $2, $3, $4, $5)
       RETURNING id`,
      [
        userId,
        collection.name,
        collection.description,
        JSON.stringify(collection.clips),
        collection.autoGenerated || false,
      ]
    );

    return result.rows[0].id;
  } catch (error) {
    console.error('Save collection error:', error);
    throw error;
  }
}

